version: '3'

services:
  proxy:
    build: ./nginx
    environment:
      - AUTH_BACKEND=http://localhost:9090
      - BACKEND=https://labs.wework.com
    ports:
      - "80:80"

  auth:
    build: ./lasso
    ports:
      - "9090:9090"

