version: '3'

services:
  auth:
    build: ./lasso
    ports:
      - "9090:9090"
    # volumes:
    #   - static:/go/src/github.com/bnfinet/lasso/static

  proxy:
    build: ./nginx
    depends_on:
      - auth
    ports:
      - "80:80"
    # volumes:
    #   - static:/go/src/github.com/bnfinet/lasso/static:ro

# volumes:
#   static:
