# lasso config
lasso:
  # logLevel: debug
  logLevel: info
  listen: 0.0.0.0
  port: 9090

  # set allowAllUsers: true to use Lasso to just accept anyone who can authenticate at the configured provider
  allowAllUsers: true

  # Setting publicAccess: true will accept all requests, even without a cookie.
  # If the user is logged in, the cookie will be validated and the user header will be set.
  # You will need to direct people to the Lasso login page from your application.
  publicAccess: false

  # each of these domains must serve the url https://lasso.$domains[0] https://lasso.$domains[1] ...
  # usually you'll just have one.
  # Comment this out if you set allowAllUser:true
  # domains:
  # - weworklabs.com
  # - yourotherdomain.com

  jwt:
    issuer: Lasso
    maxAge: 240
    secret: is_it_secret_is_it_safe
    compress: true

  cookie:
    # name of cookie to store the jwt
    name: Lasso-cookie
    # optionally force the domain of the cookie to set
    # domain: weworklabs.com
    secure: true
    httpOnly: true

  session:
    name: lasso-session

  headers:
    jwt: X-Lasso-Token
    querystring: access_token
    redirect: X-Lasso-Requested-URI

  db:
    file: data/lasso_bolt.db

  test_url: https://weworklabs.com

#
# OAuth Provider Config
#
oauth:
  # configure only one of the following

  # # Google
  # provider: google
  # # create new credentials at:
  # # https://console.developers.google.com/apis/credentials
  # client_id:
  # client_secret:
  # callback_urls:
  #   - http://lasso.weworklabs.com:9090/auth
  #   - http://lasso.yourotherdomain.com:9090/auth
  # preferredDomain: weworklabs.com

  # # GitHub
  # # https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/
  # provider: github
  # client_id:
  # client_secret:
  # auth_url: https://github.com/login/oauth/authorize
  # token_url: https://github.com/login/oauth/access_token
  # # callback_url is configured at github.com when setting up the app
  # # set to e.g. https://lasso.weworklabs.com/auth
  # scopes:
  #   - user
  # user_info_url: https://api.github.com/user?access_token=

  # Generic OpenID Connect
  provider: oidc
  client_id: 8Yl9MDoy9RZk93DzHfdF111n7Eeq09pr
  client_secret: 8s2E3SxVIHvFS8cwrjTbc5EaPCB40yf0DJPguh98xSerh_duG0-hVIkfpvM7j9wN
  auth_url: https://we-id.auth0.com/authorize
  token_url: https://we-id.auth0.com/oauth/token
  user_info_url: https://we-id.auth0.com/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: http://localhost:9090/auth

  # # IndieAuth
  # # https://indielogin.com/api
  # provider: indieauth
  # client_id: http://weworklabs.com
  # auth_url: https://indielogin.com/auth
  # callback_url: http://lasso.weworklabs.com:9090/auth

